name: Sync to Hugging Face hub
on:
  push: 
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses:  actions/checkout@v3
        with:
          fetch-depth:  0
          lfs: true
      
      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      
      - name: Pull from Hugging Face
        env:
          HF_TOKEN:  ${{ secrets.HF_TOKEN }}
        run: git pull https://akshaybgundale:$HF_TOKEN@huggingface. co/spaces/akshaybgundale/search_engine_llm_and_agents main --allow-unrelated-histories
      
      - name: Push to Hugging Face
        env:
          HF_TOKEN:  ${{ secrets.HF_TOKEN }}
        run: git push https://akshaybgundale:$HF_TOKEN@huggingface.co/spaces/akshaybgundale/search_engine_llm_and_agents main
